### ISSUE TITLE
How is it different from cordova, phonegap

### ISSUE THREAD

**Issue by shriharip** [android-js/androidjs#13]
hi,

Could you also elaborate or let users know how this is different from other libraries/framework out there? When should users use this etc. in the readme?

**Comment by Chhekur** [comment]
Hi,
it is different from cordova and phonegap because they just provide you support only for front end.
they don't provide any kind of backend support, so in this case you have to make your app as API based which fetches data from server and loads into the android webview.

but in `Android JS` it provide you Node JS runtime environment to write the backend logics of your code inside the app no need to fetch the data from server.
you can use NPM packages inside your app like Socket.io , fs to read/write files from android storage and many more.

Sure we will definitely add How Android JS is different from other framework available there on website and as well as README

If you have any doubts, you can writes us any time.


Thanks!
