### ISSUE TITLE
My app works fine on browser but not in my mobile

### ISSUE THREAD

**Issue by k2helix** [android-js/androidjs#154]
Hello, I started using AndroidJS to make my app. I made my app, and I was testing it in my browser (the html file), and all was working fine. When I finished, I built the apk and installed it into my phone, but all the things that need the back or the front to send something didn't work.

I was using the Brave browser and my mobile is Sony Xperia XA2 (I don't think this to be the problem)
Thanks in advance.

**Comment by Chhekur** [comment]
Hey @Trunks8257 ,
Could you please check the logcats of the app because I am pretty sure, there should be some error in back process if app is crashing in phone.

**Comment by Trunks8257** [comment]
@Chhekur , I found the error. My app needs of a JSON file to work, but idk why the builder wasn't adding it. I simply copied the file and pasted into userData folder and it worked. My app's structure is: 
![image](https://user-images.githubusercontent.com/49949593/101366718-9675e480-38a5-11eb-86ac-2016f5170c80.png)

**Comment by Chhekur** [comment]
Builder adds everything available in your project directory, may be error was because of wrong path because when you open the app in phone it loads everything in the memory.
So that could be the case path was wrong or something and in case of androids external directory which is always going to same path at that's why that works.

**Comment by codewithkrishnab** [comment]
Same Issue!! Back and Front can't contact with each other any suggestions?
