### ISSUE TITLE
Status bar is appearing in full screen mode

### ISSUE THREAD

**Issue by nmagko** [android-js/androidjs#168]
Hi there,

After android-sdk was updated to 2.2.0 with "androidjs u" full screen mode is showing the status bar.

Is there a new attribute in package.json to hide status bar?

    "theme": {
        "fullScreen": true
    }

Thanks
Victor C.

**Comment by MrMaxie** [comment]
Hello, im trying to use AndroidJS, but sadly this awesome library does not allow to fullscreen at current state, maybe because of that update which you mentioned, idk.

At trying to fix by myself without knowing much about Android itself and I found how to fix it. Try to find caches of android application used at building and find there such file, e.g in Windows i have it under such location: `C:\Users\MY_USERNAME\.androidjs\cache\androidjs-sdk\res\values\styles.xml`, edit this file (for keeping building process working well all the time, you can just write JS code for building and hotfix it always before such building using npm scripts e.g `"build": "node my-hotfix.js && androidjs build"`). Inside this file find node `style[name="AppTheme"]` and add inside such children:
```xml
<item name="android:windowFullscreen">true</item>
```
I hope it will work for you too! ❤

**Comment by nmagko** [comment]
A simple workaround for this issue:
- Clean ~/.androidjs folder.
- Update androidjs to 2.2.4 and androidjs SDK to 2.0.4.
- Add fullScreen and colorPrimaryDark attributes in package.json file. By setting colorPrimaryDark with same color as background worked for me.

    "theme": {
        "fullScreen": true,
	"colorPrimaryDark": "#000000"
    }
