### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by SanaRinomi** [android-js/androidjs#84]
**Is your feature request related to a problem? Please describe.**
Templating systems implemented within the HTML require more code and clutters the file.

**Describe the solution you'd like**
Adding the possibility to render the HTML on the backend to later push it out to the browser window.

**Additional context**
I'm someone who likes to use Handlebars when developing with Electron or Express servers.
I also know many people who prefer to use template systems with their websites.

**Comment by Chhekur** [comment]
You can actually use any templating engine, you just need to build an `express server` in `main.js` and then you can configure any `templating engine` you like and can start coding in that.
So basically you are serving `pages` from `express server` on a particular port, so in order to access that you just have to url redirection rule in `index.html` file then you will good to go.

Feel free to ask anything or any doubt ; )

**Comment by SanaRinomi** [comment]
Oh I see! I didn't even consider that possibility.

Ofc, now that you say that it makes perfect sense that you'd be abled to do
such a thing with a standard nodejs server that's essentially running on
mobile!
