### ISSUE TITLE
MongoDB Atlas and AndroidJS

### ISSUE THREAD

**Issue by DisturbeD-347939** [android-js/androidjs#89]
Using MongoDB atlas on android doesn't work, if I ran it from my laptop however, it works perfectly. Does anyone know any database which could possibly work with androidjs?

1. Create a MongoDB Atlas cluster
2. Connect it to your nodejs app
3. Create the apk
4. Test the connection

**Comment by Chhekur** [comment]
Hey,
this is the problem with the `node version`

In order to make it work you need to select `Node.js` version to `2.2.12 or later` instead of `3.0` while generating the `mongo atlas` connection string.
Checkout the screenshot below.

Feel free to write in case of any problem ; )

<img width="699" alt="image" src="https://user-images.githubusercontent.com/18138383/76162582-16c7b780-6165-11ea-878b-5908c6478b2b.png">

**Comment by DisturbeD-347939** [comment]
Heya,

That fixed the issue, thanks for the quick reply!

**Comment by emartisoft** [comment]
Hi,
To connect to cluster via Node.js:
> In order to make it work you need to select Node.js version to 2.2.12 or later instead of 3.0 while generating the mongo atlas connection string.

Any changes for Node.js version? How to know android js uses what node.js version?
