### ISSUE TITLE
Key for update app on play store

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs#92]
I would upload my app in play store, but i have a basic question:
TO upload i need that the app is signed, and to update it i need the same key to resign the updated .apk, so how does it work with androidjs? I need to do something if i need to  update the app or i simply repackage the  update with the same project? Thank you

**Comment by Chhekur** [comment]
> I would upload my app in play store, but i have a basic question:
> TO upload i need that the app is signed, and to update it i need the same key to resign the updated .apk, so how does it work with androidjs? I need to do something if i need to update the app or i simply repackage the update with the same project? Thank you

Right now we just sign the apk with temporary key, in order to sign apk with your specific key
- Generate your own keystore
- Follow these instruction [https://github.com/patrickfav/uber-apk-signer](https://github.com/patrickfav/uber-apk-signer) to sign the apk with your release keystore

In future build we'll provide sign command as well thanks for the good suggestion ; )

Feel free to ask in case of any problem ; )

**Comment by Chhekur** [comment]
Hey, we have created a slack channel for support & discussion: [join here](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ)
